### ISSUE TITLE
Error generating data using default tokenizer

### ISSUE THREAD

**Issue by gohjiayi** [smitkiri/ehr-relation-extraction#11] opened 2021-12-20 13:58 UTC
Hi, thank you so much for your repository, it has been extremely helpful for me in my research work. 

Would like to highlight this particular issue when running `generate_data.py` when using the default tokenizer (not applicable to the scispacy tokenizer which is the current default).

The following error is encountered
```
$ python3 -m app.training.generate_data

Reading data

Train data:
Progress: [====================] 303/303

Test Data:
Progress: [==========>         ] 103/202/home/jiayi/adverse_drug_event_extraction/app/training/ehr.py:179: UserWarning: Invalid annotation encountered: ['12 hours']
  warnings.warn("Invalid annotation encountered: " + str(line))
Progress: [==============>     ] 145/202Traceback (most recent call last):
  File "/home/jiayi/anaconda3/envs/training/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jiayi/anaconda3/envs/training/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jiayi/adverse_drug_event_extraction/app/training/generate_data.py", line 214, in <module>
    main()
  File "/home/jiayi/adverse_drug_event_extraction/app/training/generate_data.py", line 175, in main
    train_dev, test = read_data(data_dir=args.input_dir,
  File "/home/jiayi/adverse_drug_event_extraction/app/training/utils.py", line 293, in read_data
    record = HealthRecord(fid, text_path=os.path.join(test_path, fid + '.txt'),
  File "/home/jiayi/adverse_drug_event_extraction/app/training/ehr.py", line 62, in __init__
    self.set_tokenizer(tokenizer)
  File "/home/jiayi/adverse_drug_event_extraction/app/training/ehr.py", line 269, in set_tokenizer
    self._compute_tokens()
  File "/home/jiayi/adverse_drug_event_extraction/app/training/ehr.py", line 226, in _compute_tokens
    raise Exception("Error computing token to char map.")
Exception: Error computing token to char map.
```

After some debugging I have noticed that this is due to the 2 "###" instances in the test set for the 109724.txt file. After removing the 2 instances observed, everything was running fine. Not too sure why this is happening but thought it would be interesting to point it out for future use. Additionally, after training the model the model predictions were unexpected as well. Output was supposed to be [('ROU', 1, 1), ('DUR', 2, 2), ('DOS', 3, 3), ('ADE', 4, 4), ('FRE', 5, 6)] but it returned [('inpatient', 0, 0), ('Pseudoaneurysm', 1, 1), ('Fevers', 2, 4), ('QTc', 5, 6)].

I ended up adopting the scispacy tokenizer which works perfectly. Cheers!

**Comment by smitkiri** [comment] 2021-12-21 08:06
Hi Goh Jia Yi! Thanks for pointing out the issue. 

Here's what the error meant:
When computing the token to character map, I used two pointers, `j` and `k`. The pointer `j` goes through each character in the original text and `k` goes through each character in each token, making sure `text[j] == token[k]`. Once we reach the end of the current token, `j` is incremented until the `text[j]` matches the first character of the next token (these are usually the discarded whitespace characters). The error just meant that after doing all that, `text[j] != token[k]`, meaning the text and the token pointers are misaligned.

How I fixed it:
The BERT tokenizer splits into multiple pieces, like `surfing` is split into `["surf", "##ing"]`. It adds an extra `##` in the tokens (which is obviously not present in the original text) so I adjusted the pointer `k` to ignore this extra `##`. This was done regardless of the tokenizer type, so I added a flag to recognize if the tokenizer is a WordPiece tokenizer, and adjust for `##` only then. 

Thank you so much for narrowing the issue down to "###" occurrences, that was very useful in identifying the root cause. The fix is available in the `default_tok_fix` branch right now, I will soon merge it to the main branch after resolving some merge conflicts that I have.

Regarding the unexpected model outputs, can you give me more details about the tokenizer and the model that you used?

**Comment by gohjiayi** [comment] 2021-12-21 08:16
Thanks for the quick fix and the detailed explanation! Appreciate it.

For the unexpected model output, I was using the default tokenizer and the BiLSTM-CRF NER model. Upon switching to the scispacy tokenizer with the same model, the issue no longer persists. Unfortunately, I do not have any insights on why this is happening.

**Comment by smitkiri** [comment] 2021-12-21 13:29
Thanks for bringing up the issue! Unfortunately, I do not have the bandwidth and the resources to train a model and try to reproduce the results right now. From the outputs you mentioned, it seems like the model is taking things like "inpatient" and "Pseudoaneurysm" as annotation tags, which shouldn't happen if the format of the generated training and test file is correct (different documents separated by an empty line and each line is \<token\>\<space\>\<tag\>). 

Maybe the format got disturbed when you manually removed the "###" instance from the test file? If you have the bandwidth, can you just check to see if the training and test file used to train that specific model has the format \<token\>\<space\>\<tag\> and none of the \<tag\> is anything unexpected? 

You can also just check the `tags.txt` file that would've been generated after running `build_data.py` and make sure that the contents are just

```
I-REA
B-REA
B-DUR
O
I-DUR
I-DRUG
B-STR
B-FRE
I-DOS
B-FOR
I-FOR
B-DRUG
I-FRE
B-ADE
I-STR
B-DOS
I-ADE
B-ROU
I-ROU
```

**Comment by smitkiri** [comment] 2021-12-21 13:51
I looked into it a little bit more and the issue was simpler than I thought. The default tokenizer only splits the sequence by a space and so the new-line character still existed which messed up the format of the generated files. I changed the tokenizer to now also split by a new line. The issue should be completely fixed now.

**Closed as completed** 2021-12-21 13:55 UTC

**Comment by gohjiayi** [comment] 2021-12-21 17:10
You are right! The `tags.txt` file generated contained roughly 20k vocabularies and I was confused as to why. Thanks for the quick fix to this issue!
